name: Publish Image to VPS

on:
  [workflow_dispatch]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag cameteo:latest
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.PAT }}
    - name: Build Docker image
      run: |
        docker build -t ghcr.io/${{ lower(github.repository_owner) }}/cameteo:latest .
    - name: Push Docker image
      run: |
        docker push ghcr.io/${{ lower(github.repository_owner) }}/cameteo:latest
